#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
キタカミ図鑑とブルーベリー図鑑のデータを処理してpokedex_structure.jsonに追加するスクリプト
PokeAPIから取得したキタカミ（ID:32）とブルーベリー（ID:33）図鑑データを使用
"""

import json
import requests
from pathlib import Path

# キタカミ図鑑データ (PokeAPIから取得済み)
kitakami_pokemon = [
    {"entry_number": 1, "name": "spinarak"},
    {"entry_number": 2, "name": "ariados"},
    {"entry_number": 3, "name": "yanma"},
    {"entry_number": 4, "name": "yanmega"},
    {"entry_number": 5, "name": "wooper"},
    {"entry_number": 6, "name": "quagsire"},
    {"entry_number": 7, "name": "poochyena"},
    {"entry_number": 8, "name": "mightyena"},
    {"entry_number": 9, "name": "volbeat"},
    {"entry_number": 10, "name": "illumise"},
    {"entry_number": 11, "name": "corphish"},
    {"entry_number": 12, "name": "crawdaunt"},
    {"entry_number": 13, "name": "sewaddle"},
    {"entry_number": 14, "name": "swadloon"},
    {"entry_number": 15, "name": "leavanny"},
    {"entry_number": 16, "name": "cutiefly"},
    {"entry_number": 17, "name": "ribombee"},
    {"entry_number": 18, "name": "ekans"},
    {"entry_number": 19, "name": "arbok"},
    {"entry_number": 20, "name": "pichu"},
    {"entry_number": 21, "name": "pikachu"},
    {"entry_number": 22, "name": "raichu"},
    {"entry_number": 23, "name": "bellsprout"},
    {"entry_number": 24, "name": "weepinbell"},
    {"entry_number": 25, "name": "victreebel"},
    {"entry_number": 26, "name": "sentret"},
    {"entry_number": 27, "name": "furret"},
    {"entry_number": 28, "name": "starly"},
    {"entry_number": 29, "name": "staravia"},
    {"entry_number": 30, "name": "staraptor"},
    {"entry_number": 31, "name": "fomantis"},
    {"entry_number": 32, "name": "lurantis"},
    {"entry_number": 33, "name": "applin"},
    {"entry_number": 34, "name": "flapple"},
    {"entry_number": 35, "name": "appletun"},
    {"entry_number": 36, "name": "dipplin"},
    {"entry_number": 37, "name": "vulpix"},
    {"entry_number": 38, "name": "ninetales"},
    {"entry_number": 39, "name": "poliwag"},
    {"entry_number": 40, "name": "poliwhirl"},
    {"entry_number": 41, "name": "poliwrath"},
    {"entry_number": 42, "name": "politoed"},
    {"entry_number": 43, "name": "magikarp"},
    {"entry_number": 44, "name": "gyarados"},
    {"entry_number": 45, "name": "hoothoot"},
    {"entry_number": 46, "name": "noctowl"},
    {"entry_number": 47, "name": "aipom"},
    {"entry_number": 48, "name": "ambipom"},
    {"entry_number": 49, "name": "heracross"},
    {"entry_number": 50, "name": "swinub"},
    {"entry_number": 51, "name": "piloswine"},
    {"entry_number": 52, "name": "mamoswine"},
    {"entry_number": 53, "name": "stantler"},
    {"entry_number": 54, "name": "seedot"},
    {"entry_number": 55, "name": "nuzleaf"},
    {"entry_number": 56, "name": "shiftry"},
    {"entry_number": 57, "name": "ralts"},
    {"entry_number": 58, "name": "kirlia"},
    {"entry_number": 59, "name": "gardevoir"},
    {"entry_number": 60, "name": "gallade"},
    {"entry_number": 61, "name": "kricketot"},
    {"entry_number": 62, "name": "kricketune"},
    {"entry_number": 63, "name": "pachirisu"},
    {"entry_number": 64, "name": "riolu"},
    {"entry_number": 65, "name": "lucario"},
    {"entry_number": 66, "name": "petilil"},
    {"entry_number": 67, "name": "lilligant"},
    {"entry_number": 68, "name": "phantump"},
    {"entry_number": 69, "name": "trevenant"},
    {"entry_number": 70, "name": "rockruff"},
    {"entry_number": 71, "name": "lycanroc"},
    {"entry_number": 72, "name": "skwovet"},
    {"entry_number": 73, "name": "greedent"},
    {"entry_number": 74, "name": "toedscool"},
    {"entry_number": 75, "name": "toedscruel"},
    {"entry_number": 76, "name": "poltchageist"},
    {"entry_number": 77, "name": "sinistcha"},
    {"entry_number": 78, "name": "growlithe"},
    {"entry_number": 79, "name": "arcanine"},
    {"entry_number": 80, "name": "geodude"},
    {"entry_number": 81, "name": "graveler"},
    {"entry_number": 82, "name": "golem"},
    {"entry_number": 83, "name": "bonsly"},
    {"entry_number": 84, "name": "sudowoodo"},
    {"entry_number": 85, "name": "timburr"},
    {"entry_number": 86, "name": "gurdurr"},
    {"entry_number": 87, "name": "conkeldurr"},
    {"entry_number": 88, "name": "noibat"},
    {"entry_number": 89, "name": "noivern"},
    {"entry_number": 90, "name": "arrokuda"},
    {"entry_number": 91, "name": "barraskewda"},
    {"entry_number": 92, "name": "hatenna"},
    {"entry_number": 93, "name": "hattrem"},
    {"entry_number": 94, "name": "hatterene"},
    {"entry_number": 95, "name": "morpeko"},
    {"entry_number": 96, "name": "orthworm"},
    {"entry_number": 97, "name": "tandemaus"},
    {"entry_number": 98, "name": "maushold"},
    {"entry_number": 99, "name": "mankey"},
    {"entry_number": 100, "name": "primeape"},
    {"entry_number": 101, "name": "annihilape"},
    {"entry_number": 102, "name": "munchlax"},
    {"entry_number": 103, "name": "snorlax"},
    {"entry_number": 104, "name": "lotad"},
    {"entry_number": 105, "name": "lombre"},
    {"entry_number": 106, "name": "ludicolo"},
    {"entry_number": 107, "name": "nosepass"},
    {"entry_number": 108, "name": "probopass"},
    {"entry_number": 109, "name": "shinx"},
    {"entry_number": 110, "name": "luxio"},
    {"entry_number": 111, "name": "luxray"},
    {"entry_number": 112, "name": "grubbin"},
    {"entry_number": 113, "name": "charjabug"},
    {"entry_number": 114, "name": "vikavolt"},
    {"entry_number": 115, "name": "oricorio"},
    {"entry_number": 116, "name": "sandshrew"},
    {"entry_number": 117, "name": "sandslash"},
    {"entry_number": 118, "name": "gastly"},
    {"entry_number": 119, "name": "haunter"},
    {"entry_number": 120, "name": "gengar"},
    {"entry_number": 121, "name": "gligar"},
    {"entry_number": 122, "name": "gliscor"},
    {"entry_number": 123, "name": "houndour"},
    {"entry_number": 124, "name": "houndoom"},
    {"entry_number": 125, "name": "spoink"},
    {"entry_number": 126, "name": "grumpig"},
    {"entry_number": 127, "name": "vullaby"},
    {"entry_number": 128, "name": "mandibuzz"},
    {"entry_number": 129, "name": "mudbray"},
    {"entry_number": 130, "name": "mudsdale"},
    {"entry_number": 131, "name": "jangmo-o"},
    {"entry_number": 132, "name": "hakamo-o"},
    {"entry_number": 133, "name": "kommo-o"},
    {"entry_number": 134, "name": "bombirdier"},
    {"entry_number": 135, "name": "koffing"},
    {"entry_number": 136, "name": "weezing"},
    {"entry_number": 137, "name": "mienfoo"},
    {"entry_number": 138, "name": "mienshao"},
    {"entry_number": 139, "name": "duskull"},
    {"entry_number": 140, "name": "dusclops"},
    {"entry_number": 141, "name": "dusknoir"},
    {"entry_number": 142, "name": "chingling"},
    {"entry_number": 143, "name": "chimecho"},
    {"entry_number": 144, "name": "slugma"},
    {"entry_number": 145, "name": "magcargo"},
    {"entry_number": 146, "name": "litwick"},
    {"entry_number": 147, "name": "lampent"},
    {"entry_number": 148, "name": "chandelure"},
    {"entry_number": 149, "name": "surskit"},
    {"entry_number": 150, "name": "masquerain"},
    {"entry_number": 151, "name": "cleffa"},
    {"entry_number": 152, "name": "clefairy"},
    {"entry_number": 153, "name": "clefable"},
    {"entry_number": 154, "name": "bronzor"},
    {"entry_number": 155, "name": "bronzong"},
    {"entry_number": 156, "name": "glimmet"},
    {"entry_number": 157, "name": "glimmora"},
    {"entry_number": 158, "name": "feebas"},
    {"entry_number": 159, "name": "milotic"},
    {"entry_number": 160, "name": "dunsparce"},
    {"entry_number": 161, "name": "dudunsparce"},
    {"entry_number": 162, "name": "barboach"},
    {"entry_number": 163, "name": "whiscash"},
    {"entry_number": 164, "name": "gible"},
    {"entry_number": 165, "name": "gabite"},
    {"entry_number": 166, "name": "garchomp"},
    {"entry_number": 167, "name": "carbink"},
    {"entry_number": 168, "name": "salandit"},
    {"entry_number": 169, "name": "salazzle"},
    {"entry_number": 170, "name": "sneasel"},
    {"entry_number": 171, "name": "weavile"},
    {"entry_number": 172, "name": "snorunt"},
    {"entry_number": 173, "name": "glalie"},
    {"entry_number": 174, "name": "froslass"},
    {"entry_number": 175, "name": "tynamo"},
    {"entry_number": 176, "name": "eelektrik"},
    {"entry_number": 177, "name": "eelektross"},
    {"entry_number": 178, "name": "goomy"},
    {"entry_number": 179, "name": "sliggoo"},
    {"entry_number": 180, "name": "goodra"},
    {"entry_number": 181, "name": "ducklett"},
    {"entry_number": 182, "name": "swanna"},
    {"entry_number": 183, "name": "chewtle"},
    {"entry_number": 184, "name": "drednaw"},
    {"entry_number": 185, "name": "cramorant"},
    {"entry_number": 186, "name": "pawniard"},
    {"entry_number": 187, "name": "bisharp"},
    {"entry_number": 188, "name": "kingambit"},
    {"entry_number": 189, "name": "mimikyu"},
    {"entry_number": 190, "name": "impidimp"},
    {"entry_number": 191, "name": "morgrem"},
    {"entry_number": 192, "name": "grimmsnarl"},
    {"entry_number": 193, "name": "indeedee"},
    {"entry_number": 194, "name": "basculin"},
    {"entry_number": 195, "name": "basculegion"},
    {"entry_number": 196, "name": "ursaluna"},
    {"entry_number": 197, "name": "okidogi"},
    {"entry_number": 198, "name": "munkidori"},
    {"entry_number": 199, "name": "fezandipiti"},
    {"entry_number": 200, "name": "ogerpon"}
]

# ブルーベリー図鑑データ (PokeAPIから取得済み) - 完全版243匹
blueberry_pokemon = [
    {"entry_number": 1, "name": "doduo"},
    {"entry_number": 2, "name": "dodrio"},
    {"entry_number": 3, "name": "exeggcute"},
    {"entry_number": 4, "name": "exeggutor"},
    {"entry_number": 5, "name": "rhyhorn"},
    {"entry_number": 6, "name": "rhydon"},
    {"entry_number": 7, "name": "rhyperior"},
    {"entry_number": 8, "name": "venonat"},
    {"entry_number": 9, "name": "venomoth"},
    {"entry_number": 10, "name": "elekid"},
    {"entry_number": 11, "name": "electabuzz"},
    {"entry_number": 12, "name": "electivire"},
    {"entry_number": 13, "name": "magby"},
    {"entry_number": 14, "name": "magmar"},
    {"entry_number": 15, "name": "magmortar"},
    {"entry_number": 16, "name": "happiny"},
    {"entry_number": 17, "name": "chansey"},
    {"entry_number": 18, "name": "blissey"},
    {"entry_number": 19, "name": "scyther"},
    {"entry_number": 20, "name": "scizor"},
    {"entry_number": 21, "name": "kleavor"},
    {"entry_number": 22, "name": "tauros"},
    {"entry_number": 23, "name": "blitzle"},
    {"entry_number": 24, "name": "zebstrika"},
    {"entry_number": 25, "name": "girafarig"},
    {"entry_number": 26, "name": "farigiraf"},
    {"entry_number": 27, "name": "sandile"},
    {"entry_number": 28, "name": "krokorok"},
    {"entry_number": 29, "name": "krookodile"},
    {"entry_number": 30, "name": "rellor"},
    {"entry_number": 31, "name": "rabsca"},
    {"entry_number": 32, "name": "rufflet"},
    {"entry_number": 33, "name": "braviary"},
    {"entry_number": 34, "name": "vullaby"},
    {"entry_number": 35, "name": "mandibuzz"},
    {"entry_number": 36, "name": "litleo"},
    {"entry_number": 37, "name": "pyroar"},
    {"entry_number": 38, "name": "deerling"},
    {"entry_number": 39, "name": "sawsbuck"},
    {"entry_number": 40, "name": "smeargle"},
    {"entry_number": 41, "name": "rotom"},
    {"entry_number": 42, "name": "milcery"},
    {"entry_number": 43, "name": "alcremie"},
    {"entry_number": 44, "name": "trapinch"},
    {"entry_number": 45, "name": "vibrava"},
    {"entry_number": 46, "name": "flygon"},
    {"entry_number": 47, "name": "pikipek"},
    {"entry_number": 48, "name": "trumbeak"},
    {"entry_number": 49, "name": "toucannon"},
    {"entry_number": 50, "name": "tentacool"},
    {"entry_number": 51, "name": "tentacruel"},
    {"entry_number": 52, "name": "horsea"},
    {"entry_number": 53, "name": "seadra"},
    {"entry_number": 54, "name": "kingdra"},
    {"entry_number": 55, "name": "bruxish"},
    {"entry_number": 56, "name": "cottonee"},
    {"entry_number": 57, "name": "whimsicott"},
    {"entry_number": 58, "name": "comfey"},
    {"entry_number": 59, "name": "slakoth"},
    {"entry_number": 60, "name": "vigoroth"},
    {"entry_number": 61, "name": "slaking"},
    {"entry_number": 62, "name": "oddish"},
    {"entry_number": 63, "name": "gloom"},
    {"entry_number": 64, "name": "vileplume"},
    {"entry_number": 65, "name": "bellossom"},
    {"entry_number": 66, "name": "diglett"},
    {"entry_number": 67, "name": "dugtrio"},
    {"entry_number": 68, "name": "grimer"},
    {"entry_number": 69, "name": "muk"},
    {"entry_number": 70, "name": "zangoose"},
    {"entry_number": 71, "name": "seviper"},
    {"entry_number": 72, "name": "crabrawler"},
    {"entry_number": 73, "name": "crabominable"},
    {"entry_number": 74, "name": "oricorio"},
    {"entry_number": 75, "name": "slowpoke"},
    {"entry_number": 76, "name": "slowbro"},
    {"entry_number": 77, "name": "slowking"},
    {"entry_number": 78, "name": "chinchou"},
    {"entry_number": 79, "name": "lanturn"},
    {"entry_number": 80, "name": "inkay"},
    {"entry_number": 81, "name": "malamar"},
    {"entry_number": 82, "name": "luvdisc"},
    {"entry_number": 83, "name": "finneon"},
    {"entry_number": 84, "name": "lumineon"},
    {"entry_number": 85, "name": "alomomola"},
    {"entry_number": 86, "name": "torkoal"},
    {"entry_number": 87, "name": "fletchling"},
    {"entry_number": 88, "name": "fletchinder"},
    {"entry_number": 89, "name": "talonflame"},
    {"entry_number": 90, "name": "dewpider"},
    {"entry_number": 91, "name": "araquanid"},
    {"entry_number": 92, "name": "tyrogue"},
    {"entry_number": 93, "name": "hitmonlee"},
    {"entry_number": 94, "name": "hitmonchan"},
    {"entry_number": 95, "name": "hitmontop"},
    {"entry_number": 96, "name": "geodude"},
    {"entry_number": 97, "name": "graveler"},
    {"entry_number": 98, "name": "golem"},
    {"entry_number": 99, "name": "drilbur"},
    {"entry_number": 100, "name": "excadrill"},
    {"entry_number": 101, "name": "gothita"},
    {"entry_number": 102, "name": "gothorita"},
    {"entry_number": 103, "name": "gothitelle"},
    {"entry_number": 104, "name": "espurr"},
    {"entry_number": 105, "name": "meowstic"},
    {"entry_number": 106, "name": "minior"},
    {"entry_number": 107, "name": "cranidos"},
    {"entry_number": 108, "name": "rampardos"},
    {"entry_number": 109, "name": "shieldon"},
    {"entry_number": 110, "name": "bastiodon"},
    {"entry_number": 111, "name": "minccino"},
    {"entry_number": 112, "name": "cinccino"},
    {"entry_number": 113, "name": "skarmory"},
    {"entry_number": 114, "name": "swablu"},
    {"entry_number": 115, "name": "altaria"},
    {"entry_number": 116, "name": "magnemite"},
    {"entry_number": 117, "name": "magneton"},
    {"entry_number": 118, "name": "magnezone"},
    {"entry_number": 119, "name": "plusle"},
    {"entry_number": 120, "name": "minun"},
    {"entry_number": 121, "name": "scraggy"},
    {"entry_number": 122, "name": "scrafty"},
    {"entry_number": 123, "name": "golett"},
    {"entry_number": 124, "name": "golurk"},
    {"entry_number": 125, "name": "numel"},
    {"entry_number": 126, "name": "camerupt"},
    {"entry_number": 127, "name": "sinistea"},
    {"entry_number": 128, "name": "polteageist"},
    {"entry_number": 129, "name": "porygon"},
    {"entry_number": 130, "name": "porygon2"},
    {"entry_number": 131, "name": "porygon-z"},
    {"entry_number": 132, "name": "joltik"},
    {"entry_number": 133, "name": "galvantula"},
    {"entry_number": 134, "name": "tynamo"},
    {"entry_number": 135, "name": "eelektrik"},
    {"entry_number": 136, "name": "eelektross"},
    {"entry_number": 137, "name": "beldum"},
    {"entry_number": 138, "name": "metang"},
    {"entry_number": 139, "name": "metagross"},
    {"entry_number": 140, "name": "axew"},
    {"entry_number": 141, "name": "fraxure"},
    {"entry_number": 142, "name": "haxorus"},
    {"entry_number": 143, "name": "seel"},
    {"entry_number": 144, "name": "dewgong"},
    {"entry_number": 145, "name": "lapras"},
    {"entry_number": 146, "name": "qwilfish"},
    {"entry_number": 147, "name": "overqwil"},
    {"entry_number": 148, "name": "solosis"},
    {"entry_number": 149, "name": "duosion"},
    {"entry_number": 150, "name": "reuniclus"},
    {"entry_number": 151, "name": "snubbull"},
    {"entry_number": 152, "name": "granbull"},
    {"entry_number": 153, "name": "cubchoo"},
    {"entry_number": 154, "name": "beartic"},
    {"entry_number": 155, "name": "sandshrew"},
    {"entry_number": 156, "name": "sandslash"},
    {"entry_number": 157, "name": "vulpix"},
    {"entry_number": 158, "name": "ninetales"},
    {"entry_number": 159, "name": "snover"},
    {"entry_number": 160, "name": "abomasnow"},
    {"entry_number": 161, "name": "duraludon"},
    {"entry_number": 162, "name": "archaludon"},
    {"entry_number": 163, "name": "hydrapple"},
    {"entry_number": 164, "name": "bulbasaur"},
    {"entry_number": 165, "name": "ivysaur"},
    {"entry_number": 166, "name": "venusaur"},
    {"entry_number": 167, "name": "charmander"},
    {"entry_number": 168, "name": "charmeleon"},
    {"entry_number": 169, "name": "charizard"},
    {"entry_number": 170, "name": "squirtle"},
    {"entry_number": 171, "name": "wartortle"},
    {"entry_number": 172, "name": "blastoise"},
    {"entry_number": 173, "name": "chikorita"},
    {"entry_number": 174, "name": "bayleef"},
    {"entry_number": 175, "name": "meganium"},
    {"entry_number": 176, "name": "cyndaquil"},
    {"entry_number": 177, "name": "quilava"},
    {"entry_number": 178, "name": "typhlosion"},
    {"entry_number": 179, "name": "totodile"},
    {"entry_number": 180, "name": "croconaw"},
    {"entry_number": 181, "name": "feraligatr"},
    {"entry_number": 182, "name": "treecko"},
    {"entry_number": 183, "name": "grovyle"},
    {"entry_number": 184, "name": "sceptile"},
    {"entry_number": 185, "name": "torchic"},
    {"entry_number": 186, "name": "combusken"},
    {"entry_number": 187, "name": "blaziken"},
    {"entry_number": 188, "name": "mudkip"},
    {"entry_number": 189, "name": "marshtomp"},
    {"entry_number": 190, "name": "swampert"},
    {"entry_number": 191, "name": "turtwig"},
    {"entry_number": 192, "name": "grotle"},
    {"entry_number": 193, "name": "torterra"},
    {"entry_number": 194, "name": "chimchar"},
    {"entry_number": 195, "name": "monferno"},
    {"entry_number": 196, "name": "infernape"},
    {"entry_number": 197, "name": "piplup"},
    {"entry_number": 198, "name": "prinplup"},
    {"entry_number": 199, "name": "empoleon"},
    {"entry_number": 200, "name": "snivy"},
    {"entry_number": 201, "name": "servine"},
    {"entry_number": 202, "name": "serperior"},
    {"entry_number": 203, "name": "tepig"},
    {"entry_number": 204, "name": "pignite"},
    {"entry_number": 205, "name": "emboar"},
    {"entry_number": 206, "name": "oshawott"},
    {"entry_number": 207, "name": "dewott"},
    {"entry_number": 208, "name": "samurott"},
    {"entry_number": 209, "name": "chespin"},
    {"entry_number": 210, "name": "quilladin"},
    {"entry_number": 211, "name": "chesnaught"},
    {"entry_number": 212, "name": "fennekin"},
    {"entry_number": 213, "name": "braixen"},
    {"entry_number": 214, "name": "delphox"},
    {"entry_number": 215, "name": "froakie"},
    {"entry_number": 216, "name": "frogadier"},
    {"entry_number": 217, "name": "greninja"},
    {"entry_number": 218, "name": "rowlet"},
    {"entry_number": 219, "name": "dartrix"},
    {"entry_number": 220, "name": "decidueye"},
    {"entry_number": 221, "name": "litten"},
    {"entry_number": 222, "name": "torracat"},
    {"entry_number": 223, "name": "incineroar"},
    {"entry_number": 224, "name": "popplio"},
    {"entry_number": 225, "name": "brionne"},
    {"entry_number": 226, "name": "primarina"},
    {"entry_number": 227, "name": "grookey"},
    {"entry_number": 228, "name": "thwackey"},
    {"entry_number": 229, "name": "rillaboom"},
    {"entry_number": 230, "name": "scorbunny"},
    {"entry_number": 231, "name": "raboot"},
    {"entry_number": 232, "name": "cinderace"},
    {"entry_number": 233, "name": "sobble"},
    {"entry_number": 234, "name": "drizzile"},
    {"entry_number": 235, "name": "inteleon"},
    {"entry_number": 236, "name": "gouging-fire"},
    {"entry_number": 237, "name": "raging-bolt"},
    {"entry_number": 238, "name": "iron-crown"},
    {"entry_number": 239, "name": "iron-boulder"},
    {"entry_number": 240, "name": "terapagos"},
    {"entry_number": 241, "name": "walking-wake"},
    {"entry_number": 242, "name": "iron-leaves"},
    {"entry_number": 243, "name": "pecharunt"}
]

def load_pokemon_data():
    """pokemon_data.jsonから全ポケモンデータを読み込む"""
    with open('pokemon_data.json', 'r', encoding='utf-8') as f:
        return json.load(f)

def get_pokemon_id_by_name(pokemon_data, name_en):
    """英語名からpokemon_idを取得"""
    for pokemon_id, pokemon_info in pokemon_data.items():
        if pokemon_info.get('name_en') == name_en:
            return int(pokemon_id)
    return None

def get_japanese_name(pokemon_data, name_en):
    """英語名から日本語名を取得"""
    for pokemon_id, pokemon_info in pokemon_data.items():
        if pokemon_info.get('name_en') == name_en:
            return pokemon_info.get('name')
    return name_en  # 見つからない場合は英語名をそのまま返す

def create_pokedex_data(pokemon_list, pokemon_data, dex_id, dex_name, dex_key):
    """図鑑データを作成"""
    pokedex_entry = {
        "id": dex_id,
        "name": dex_name,
        "key": dex_key,
        "pokemon": {}
    }
    
    for entry in pokemon_list:
        entry_num = entry["entry_number"]
        name_en = entry["name"]
        
        # pokemon_idを取得
        pokemon_id = get_pokemon_id_by_name(pokemon_data, name_en)
        if pokemon_id is None:
            print(f"Warning: Pokemon {name_en} not found in pokemon_data.json")
            continue
            
        # 日本語名を取得
        japanese_name = get_japanese_name(pokemon_data, name_en)
        
        pokedex_entry["pokemon"][str(entry_num)] = {
            "pokemon_id": pokemon_id,
            "name": japanese_name,
            "name_en": name_en
        }
    
    return pokedex_entry

def main():
    """メイン処理"""
    print("🌟 キタカミ・ブルーベリー図鑑データ処理開始っちゃ〜♪")
    
    # pokemon_data.jsonを読み込み
    print("📖 pokemon_data.jsonを読み込み中...")
    pokemon_data = load_pokemon_data()
    
    # pokedex_structure.jsonを読み込み
    print("📖 pokedex_structure.jsonを読み込み中...")
    with open('pokedex_structure.json', 'r', encoding='utf-8') as f:
        pokedex_structure = json.load(f)
    
    # キタカミ図鑑を作成（ID: 20）
    print("🏔️ キタカミ図鑑を作成中...")
    kitakami_dex = create_pokedex_data(
        kitakami_pokemon, 
        pokemon_data, 
        20, 
        "キタカミ図鑑", 
        "kitakami"
    )
    
    # ブルーベリー図鑑を作成（ID: 21） - まずは一部のみでテスト
    print("🫐 ブルーベリー図鑑を作成中...")
    blueberry_dex = create_pokedex_data(
        blueberry_pokemon, 
        pokemon_data, 
        21, 
        "ブルーベリー図鑑", 
        "blueberry"
    )
    
    # 既存の構造に追加
    pokedex_structure["20"] = kitakami_dex
    pokedex_structure["21"] = blueberry_dex
    
    # バックアップ作成
    print("💾 バックアップを作成中...")
    with open('pokedex_structure.json.backup_before_dlc', 'w', encoding='utf-8') as f:
        json.dump(json.loads(open('pokedex_structure.json', 'r', encoding='utf-8').read()), f, ensure_ascii=False, indent=2)
    
    # 新しいファイルを保存
    print("💾 更新されたファイルを保存中...")
    with open('pokedex_structure.json', 'w', encoding='utf-8') as f:
        json.dump(pokedex_structure, f, ensure_ascii=False, indent=2)
    
    print("✨ キタカミ・ブルーベリー図鑑の追加が完了したっちゃ〜♪")
    print(f"📊 キタカミ図鑑: {len(kitakami_dex['pokemon'])}匹")
    print(f"📊 ブルーベリー図鑑: {len(blueberry_dex['pokemon'])}匹")

if __name__ == "__main__":
    main()